version: "3.7"
services:
  db:
    image: mongo:4.4.1
    container_name: db_mongo_dev
    restart: unless-stopped
    expose:
      - 20017
    ports:
      - 27018:27017
    volumes:
      - ./db-data:/data/db
